### PR TITLE
Add proofs for quantifier identities

### PR DESCRIPTION
**Pull request by michaelgwelch**
I think these are good practice before tackling the final proof of Session 6. Plus the second one can be used in the final proof.

Note: I haven't built locally yet to test that I don't have a typo. I'll do as soon as I can. I have some environment setup I need to do before I can build. Notably I don't have ghcjs installed.

### CODE REVIEW

**Comment by michaelgwelch** [comment]
Hmm, travis didn't like this. Perhaps I did make a typo. I'm setting up my machine to run build locally.

**Comment by nomeata** [comment]
No, that’s a problem with master (a site from where we pull JS library changed its URLs). I just pushed a fix (0428941). If that goes through on travis, then please your branch onto master, so that it is properly checked. Sorry for the nuisance.

**Comment by michaelgwelch** [comment]
Will open up a new PR with rebased commit

**Comment by nomeata** [comment]
You could have simply pushed your branch and it would have updated the PR. But a new one is fine as well.

**Comment by michaelgwelch** [comment]
Ah yes, of course.

**Pull request closed without merging**
