### PR TITLE
non-trivial exercise for session 2

### PR DESCRIPTION
**Pull request by lohner**
Have fun solving a new task :)

### CODE REVIEW

**Comment by nomeata** [comment]
Nice!

**Comment by nomeata** [comment]
Yes … I will look into that later. There is ongoing work in providing `ghcjs` in a PPA (see https://travis-ci.org/nomeata/ghcjs2gh-pages/builds/407165852 for a successful run) which will make the travis part simpler…

Patches welcome, of course :-)

**Comment by michaelgwelch** [comment]
@lohner that is a fun little proof for session 2. At first I assumed it would need some trickery not available in session 2, but quickly discovered how it's easily handled.

**Comment by nomeata** [comment]
Ok, I did some anti-bitrot. It now builds with ghc-8.2 and ghcjs-8.2, the travis setup is modernized, and the new version is (finally) online!

**Pull request merged**
