### PR TITLE
Fix unintended deselection of blocks after dragging

### PR DESCRIPTION
**Pull request by yuxuanchiadm**
Minor quality of life fix

### CODE REVIEW

**Comment by yuxuanchiadm** [comment]
LGTM😄

**Comment by nomeata** [comment]
Oh, wow, I haven’t touched this code in years. I asume you have tested it? :-]

**Comment by yuxuanchiadm** [comment]
yup tested locally

**Comment by nomeata** [comment]
:crossed_fingers:

**Comment by yuxuanchiadm** [comment]
Oops. Looks like travis build did not include contents in js-interface-wrapper.js into logic.js for some reason. GHCJS just ignored js-sources?

**Comment by nomeata** [comment]
Did you change the version of GHCJS or so? Maybe related to https://github.com/haskell/cabal/issues/5442?

**Comment by yuxuanchiadm** [comment]
No I didn't. But I just noticed we got different cabal-install version with last successful build from ppa.

Old: `Get:3 http://ppa.launchpad.net/hvr/ghc/ubuntu trusty/main amd64 cabal-install-head amd64 3.1+git20191103.2.129775a-6~14.04 [4,411 kB]`

New: `Get:3 http://ppa.launchpad.net/hvr/ghc/ubuntu trusty/main amd64 cabal-install-head amd64 2.5+git20190112.1.6a24235-6~14.04 [4,314 kB]`

**Comment by nomeata** [comment]
Maybe https://github.com/nomeata/incredible/pull/118 helps

**Comment by yuxuanchiadm** [comment]
🤞

**Comment by nomeata** [comment]
Nope, that did not help. Can you maybe debug this? I haven't touched this project in a while…

**Comment by yuxuanchiadm** [comment]
Sure. But looks like it didn't pushed to incredible-demo repo. Travis still doing it's job

**Comment by nomeata** [comment]
Oh, was I too impatient? Maybe it helped after all…

**Comment by yuxuanchiadm** [comment]
Yes. it works🎉

**Comment by nomeata** [comment]
Phew :-)

Thanks for your contrution!

**Pull request merged**
