### PR TITLE
Some javascript related fixes

### PR DESCRIPTION
**Pull request by psibi**

### CODE REVIEW

**Comment by nomeata** [comment]
Thanks! My experience in writing “high quality” JavaScript is limited, as you might have noticed. Is there a good tool that could be run as part of the test suite to make sure the code stays good?

**Comment by psibi** [comment]
@nomeata I would suggest integrating jshint with the Travis build.  Also using [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) for javascript will help greatly as code evolves.

**Comment by nomeata** [comment]
hmm, jshint is not in Debian, due to license issues. That makes it slightly more inconvenient for me to use it, but I guess I can install it manually using npm.

**Comment by NicoleRauch** [comment]
I actually prefer ESLint nowadays (having worked with jshint, then jslint, then switched to eslint)... Maybe that solves your debian issues as well?

**Comment by nomeata** [comment]
Also not in Debian. Debian and JavaScript don’t go well together, it seems...

**Pull request merged**
