### PR TITLE
adding baby steps to Session 6

### PR DESCRIPTION
**Pull request by rampion**
tried to propose this earlier, but didn't see it among the pull requests.

Basically, just adding more tasks to Session 6 to help used to existentials.

### CODE REVIEW

**Comment by nomeata** [comment]
Hmm. I’m not sure I like this from a didactic point of view. After having done the first two, the real task is just repetition. It would be better to have independent, but simpler tasks that teach you various concepts required for the real task bit by bit.

**Comment by rampion** [comment]
Good points. I'll see what else I can dig up.

**Comment by lohner** [comment]
Her are some suggestions (order of no relevance):

* A∧(∀x.P(x)) ==> ∀x.A∧P(x)
* (∃x.P(x))→A ==> ∀x.P(x)→A
* (∀x.P(x)) ∧ (∀x.Q(x)) ==> ∀x.P(x)∧Q(x)
* (∃x.P(x)) ∨ (∃x.Q(x)) ==> ∃x.P(x)∨Q(x)
* (∀x.P(x))→A ==> ∃x.P(x)→A  (this one seems to be nearly as complex as the drinker's paradox)
* ∀x.∀y.P(x,y) ==> ∀y.∀x.P(x,y)
* ∃x.∃y.P(x,y) ==> ∃y.∃x.P(x,y)
* ∃x.∀y.P(x,y) ==> ∀y.∃x.P(x,y)

**Comment by nomeata** [comment]
Looks good. Add it!

**Comment by nomeata** [comment]
Ah, this is a pull request, not a issue, so I should not reopen it for @lohner’s suggestions...

**Comment by lohner** [comment]
Added these and some more.

**Pull request closed without merging**
