### PR TITLE
Bump block count of last NAND calculus task

### PR DESCRIPTION
**Pull request by yuxuanchiadm**
[Proof](https://gist.github.com/yuxuanchiadm/5c5969cfec592fc55cee06d41d859178)

### CODE REVIEW

**Comment by yuxuanchiadm** [comment]
Heh. I can do better. 17 -> 15. [New Proof](https://gist.github.com/yuxuanchiadm/cf98b51939295c6ab760ee79318d2e08)

**Comment by b-mehta** [comment]
This is doable in 14 blocks:
[Proof](https://gist.github.com/b-mehta/59491dd17d865cff56ec80e7816cb09d)

**Comment by yuxuanchiadm** [comment]
> This is doable in 14 blocks:
> [Proof](https://gist.github.com/b-mehta/59491dd17d865cff56ec80e7816cb09d)
Ah sure. By sharing same block I just optimized.

**Comment by alreadydone** [comment]
Some custom problems for interested people to optimize .. I got 7,8,3,5,23,14,14,10,8,7,10,8,8 (didn't quite attempt to optimize)
image

**Comment by b-mehta** [comment]
My scores on these problems: 7,6,3,5,8,11,10,10,8,5,10,8,8

**Pull request merged**
